### ISSUE TITLE
[Enhancement]: dylib use rpath flag

### ISSUE THREAD

**Issue by chai2010** [KusionStack/KCLVM#127]
## Enhancement

https://github.com/KusionStack/KCLVM/blob/main/kclvm/Cargo.toml

```toml
[profile.release]
rpath = true
```
