### ISSUE TITLE
[Enhancement] Support list subscript format in KCL string like python.

### ISSUE THREAD

**Issue by Peefy** [KusionStack/KCLVM#149]
## Enhancement

The kcl code

```kcl
my_list = ['0', '1']
test = "0{0[0]}, 1{0[1]}".format(my_list) # '00, 11'
```

The YAML output 

```yaml
my_list:
- '0'
- '1'
test: 00, 11
```
