### ISSUE TITLE
A type error occurred when instantiating the schema in Rust kclvm_cli.

### ISSUE THREAD

**Issue by zong-zhe** [KusionStack/KCLVM#241]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
config.k
```
data = {
    key1: [0]
    key1 += [1]
    key2: [0]
    key2 = [1]
    key3 = [0]
    key3 = [1]
}

schema Config:
    data: [int]
    env: [{str:}] = [{key1: 1}, {key2: 2}]

config = Config {
    data = [1]
    data += [2]
    env[0]: {key2: 2}
}
```

kcl config --target native

### 2. What did you expect to see? (Required)

```
data:
  key1:
  - 0
  - 1
  key2:
  - 1
  key3:
  - 1
config:
  data:
  - 1
  - 2
  env:
  - key1: 1
    key2: 2
  - key2: 2
```

### 3. What did you see instead (Required)

```
KCL Runtime Error[E3M38] : Evaluation failure
---> File /Users/shijun/Workspace/kusion/fix-error_msg-bug/KCLVM/kclvm/runner/src/exec_data/config.k:12
12 |    env: [{str:}] = [{key1: 1}, {key2: 2}] -> Failure
expect [{str:}], got dict
```

### 4. What is your KusionStack components version? (Required)

kclvm version is 0.4.3; checksum: e07ed7af0d9bd1e86a3131714e4bd20c
