### ISSUE TITLE
kcl test tool produces reflect error when schema parameter has type hint

### ISSUE THREAD

**Issue by amyXia1994** [KusionStack/KCLVM#251]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

a. create a test file: `<dir>/main_test.k` with the following content
```
schema Person:
    name: str

schema GetName[p: Person]:
    result: str = p.name
```
b. run: `kcl-test <dir>/...`

### 2. What did you expect to see? (Required)

test pass

### 3. What did you see instead (Required)

err occurred: `FAIL <dir> err: reflect.Set: value of type *ast.Identifier is not assignable to type ast.TypeInterface%`

### 4. What is your KusionStack components version? (Required)
```
releaseVersion: v0.3.20-debug-73-test
gitInfo:
    latestTag: v0.3.20-debug-73-test
    commit: 87ea0e74d8001e05e2049baf08e2990bdcf768b0
    treeState: dirty
buildInfo:
    goVersion: go1.17.9
    GOOS: linux
    GOARCH: amd64
    numCPU: 80
    compiler: gc
    buildTime: "2022-08-05 04:24:34"
dependency:
    kclvmVersion: v0.4.2-alpha.9
    kclPluginVersion: v0.2.20
```
