### ISSUE TITLE
attribute type is incorrectly transformed into "UndefinedType" when passing attributes to protocol and rule

### ISSUE THREAD

**Issue by amyXia1994** [KusionStack/KCLVM#265]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. create file with name `policy.k` with following content:
```
protocol KubeResourceProtocol:
    svc: Service

schema Service:
    name: str

rule ServiceCheckRule for KubeResourceProtocol:
    svc.name != "123"

svc = Service {
    name: "123"
}

ServiceCheckRule {
    svc: svc
}
```
2. run ```kcl policy.k```

### 2. What did you expect to see? (Required)
the type should be transformed to `Service` and the rule should fail because the svc instance violates the validation expr.

### 3. What did you see instead (Required)

```➜  policy_test git:(master) ✗ kcl policy.k
KCL Runtime Error[E3M38] : Evaluation failure
---> File /Users/amy/work/Konfig/policy_test/policy.k:8
8 |    svc.name != "123" -> Failure
invalid value 'UndefinedType' to load attribute 'name'
```

### 4. What is your KusionStack components version? (Required)

```
releaseVersion: v0.3.24-alpha.1
gitInfo:
    latestTag: v0.3.24-alpha.1
    commit: 1777f4eb511b01863d9ae2b3a2313ac4eeac85ab
    treeState: dirty
buildInfo:
    goVersion: go1.17.9
    GOOS: linux
    GOARCH: amd64
    numCPU: 86
    compiler: gc
    buildTime: "2022-09-07 08:31:55"
dependency:
    kclvmVersion: v0.4.3-alpha.4
    kclPluginVersion: v0.2.20
```
