### ISSUE TITLE
[Bug] The configuration unification at compile time does not meet the expectation when the attribute with the same name has a syntax node of non-configured type e.g. ConfigExpr and SchemaExpr

### ISSUE THREAD

**Issue by Peefy** [KusionStack/KCLVM#422]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Write the kcl code (main.k)

```python
schema Resource:
    cpu: int
    memory: str

schema Config:
    resource: Resource

r = Resource {
    cpu = 4
    memory = "8Gi"
}

config: Config {
    resource: Resource {
        cpu = 2
        memory = "4Gi"
    }
}

config: Config {
    resource: r
}
```

Then run the command: 

```bash
kclvm_cli run main.k
```

### 2. What did you expect to see? (Required)

```yaml
r:
  cpu: 4
  memory: 8Gi
config:
  resource:
    cpu: 4
    memory: 8Gi
```

### 3. What did you see instead (Required)

```yaml
r:
  cpu: 2
  memory: 4Gi
config:
  resource:
    cpu: 2
    memory: 4Gi
```

### 4. What is your KusionStack components version? (Required)

kclvm version is 0.4.5; checksum: c5339e572207211e46477825e8aca903
