### ISSUE TITLE
Incorrect check on optional schema parameter

### ISSUE THREAD

**Issue by mihaigalos** [KusionStack/KCLVM#443]
### 1. Minimal reproduce step (Required)

Tried to run the example from the [docs](https://kcl-lang.io/docs/user_docs/guides/configuration).
```kcl
schema Person:
    gender: "Male" | "Female"
    name: Name

schema Name:
    first: str
    middle?: str  # Optional, but must be non-empty when specified
    last: str

    check:
        first != ""
        last != ""
        middle != "" if middle

alice = Person {
    gender: "Female"
    name.first: "Alice"
    name.last: "White"
    name.middle: ""
}
```
Ran with `kcl person.k`.

### 2. What did you expect to see? (Required)
```yaml
alice:
  gender: Female
  name:
    first: Alice
    last: White
```

### 3. What did you see instead (Required)
```yaml
alice:
  gender: Female
  name:
    first: Alice
    last: White
    middle: ''     <-- This should not be here!
```

### 4. What is your KusionStack components version? (Required)
I don't have this folder on my machine, since built the binaries from source (commit 82c2be097be0ae29b8a159171f0d379737bd3eba from March 8th).
