### ISSUE TITLE
[Enhancement] KCLVM CLI support settings file parse with complex structures.

### ISSUE THREAD

**Issue by Peefy** [KusionStack/KCLVM#506]
## Enhancement

For example

+ kcl.yaml

```yaml
kcl_options:
- key: env-type
  value: TEST
- key: deploy-topology
  value:
  - cluster: my-cluster
    idc: my-idc
    replicas: 2
    workspace: my-workspace
    zone: my-zone
```

kclvm_cli run -Y kcl.yaml
